name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # You can specify your preferred version of Python

    # Step 3: Run linter (flake8)
    - name: Run linter
      run: |
        pip install flake8
        flake8 src 

    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 5: Run mypy
    - name: Run mypy
      run: |
        pip install mypy
        mypy src

    # Step 6: Run your Python script (main.py or any other script)
    - name: Run Python Script
      run: |
        python src/OrcidXtract/main.py --orcid_ids 0000-0002-0970-0455 --output-format txt pdf json --report csv 

    # Step 7: Run tests
    - name: Run tests with coverage
      run: |
          coverage run -m pytest src/OrcidXtract/test.py  # Specify the exact path if necessary
          coverage report
          coverage html  # Generates an HTML report

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: Install dependencies
        run: |
          pip install '.[test]'
      - name: Run tests
        run: |
          pytest src/OrcidXtract/test.py
